favicon: /favicon.ico


# Nav Menus
menu:
    首页: /
    归档: /archives
    分类: /categories
    标签: /tags

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/lolgigeo2016']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['OpenClaw', 'AI助手框架', 'https://openclaw.ai']
    - ['文档库', '技术文档', 'http://172.238.20.139']


# About
about_info:
    name: "Vincent Zhang"
    bio: "技术笔记与项目文档"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# Analytics
google_analytics: 
tencent_analytics: 
 
# Copyright Infomation
startyear: 2026
